-- local status, skkelton = pcall(require, "skkelton")
-- if not status then
-- 	-- print("Error loading skkelton: " .. skkelton)
-- 	return
-- end

-- vim.fn["skkeleton#config"]({
-- 	globalDictionaries = {
-- 		"/usr/share/skk/SKK-JISYO.L",
-- 		"/usr/share/skk/SKK-JISYO.fullname",
-- 		"~/.skk/SKK-JISYO.L",
-- 	},
-- })
